### ISSUE TITLE
UnicodeDecodeError In SystemTray get_server_procs

### ISSUE THREAD

**Issue by becurrie** [becurrie/titandash#167]
```
Traceback (most recent call last):
  File "titandash.py", line 385, in <module>
    app = TitandashTrayApp()
  File "titandash.py", line 49, in __init__
    self.status = self.kill_server()
  File "titandash.py", line 161, in kill_server
    procs = self.get_server_procs()
  File "titandash.py", line 130, in get_server_procs
    output = output.decode().replace("\r", "").split("\n")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x99 in position 58: invalid start byte
```

**Comment by becurrie** [comment]
Resolved by #176
