### ISSUE TITLE
[BUG] ModuleNotFoundError: No module named 'contextlib'

### ISSUE THREAD

**Issue by justliamj** [becurrie/titandash#180]
This is the error I get when running **setup.bat** now;

```
C:\Users\LiaM\titandash>call mkvirtualenv titandash -r requirements.txt

    ERROR: virtualenv "titandash" already exists

Fatal Python error: initsite: Failed to import the site module
Traceback (most recent call last):
  File "C:\Users\LiaM\Envs\titandash\lib\site.py", line 769, in <module>
    main()
  File "C:\Users\LiaM\Envs\titandash\lib\site.py", line 746, in main
    paths_in_sys = addsitepackages(paths_in_sys)
  File "C:\Users\LiaM\Envs\titandash\lib\site.py", line 279, in addsitepackages
    addsitedir(sitedir, known_paths)
  File "C:\Users\LiaM\Envs\titandash\lib\site.py", line 202, in addsitedir
    addpackage(sitedir, name, known_paths)
  File "C:\Users\LiaM\Envs\titandash\lib\site.py", line 170, in addpackage
    exec(line)
  File "<string>", line 1, in <module>
  File "C:\Users\LiaM\Envs\titandash\lib\importlib\util.py", line 14, in <module>
    from contextlib import contextmanager
ModuleNotFoundError: No module named 'contextlib'
Fatal Python error: initsite: Failed to import the site module
Traceback (most recent call last):
  File "C:\Users\LiaM\Envs\titandash\lib\site.py", line 769, in <module>
    main()
  File "C:\Users\LiaM\Envs\titandash\lib\site.py", line 746, in main
    paths_in_sys = addsitepackages(paths_in_sys)
  File "C:\Users\LiaM\Envs\titandash\lib\site.py", line 279, in addsitepackages
    addsitedir(sitedir, known_paths)
  File "C:\Users\LiaM\Envs\titandash\lib\site.py", line 202, in addsitedir
    addpackage(sitedir, name, known_paths)
  File "C:\Users\LiaM\Envs\titandash\lib\site.py", line 170, in addpackage
    exec(line)
  File "<string>", line 1, in <module>
  File "C:\Users\LiaM\Envs\titandash\lib\importlib\util.py", line 14, in <module>
    from contextlib import contextmanager
ModuleNotFoundError: No module named 'contextlib'
audited 25 packages in 0.969s
found 0 vulnerabilities

The system cannot find the path specified.
Press any key to continue . . .
```

**Comment by becurrie** [comment]
Looking into this now!

**Comment by becurrie** [comment]
What version of Python are you on? `contextlib` should be part of the standard library included with python!

**Comment by justliamj** [comment]
Python 3.7.0

**Comment by becurrie** [comment]
Could you please try:
`rm virtualenv titandash`

And then run the `setup.bat` again!

I'm thinking that maybe since the original install failed halfway through, the environment exists but the install did not finish completely.

**Comment by justliamj** [comment]
Now comes up with this;

`During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\LiaM\titandash\settings.py", line 48, in <module>
    import git
  File "C:\Users\LiaM\Envs\titandash\lib\site-packages\git\__init__.py", line 85, in <module>
    raise ImportError('Failed to initialize: {0}'.format(exc))
ImportError: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh()

All git commands will error until this is rectified.

This initial warning can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|none|n|0: for no warning or exception
    - warn|w|warning|1: for a printed warning
    - error|e|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet`

**Comment by becurrie** [comment]
Great, I'm going to close this issue for now!

For anyone else coming here from a link or reference, if the virtual environment installation fails halfway through, ensure you remove the corrupt environment before attempting to setup again.
