### ISSUE TITLE
Support For Disabling Artifact Upgrades

### ISSUE THREAD

**Issue by becurrie** [becurrie/titandash#187]
Disabling artifact upgrades will currently break the prestige process.

```
[2019-09-24 13:51:35,690] INFO [Titandash Instance 3] [bot.py:737 - prestige() ] beginning prestige process in game now.
[2019-09-24 13:51:35,877] INFO [Titandash Instance 3] [bot.py:873 - check_tournament() ] checking for tournament ready to join or in progress.
[2019-09-24 13:51:44,930] INFO [Titandash Instance 3] [stats.py:319 - update_prestige() ] Attempting to parse out the time since last prestige
[2019-09-24 13:51:45,160] INFO [Titandash Instance 3] [stats.py:328 - update_prestige() ] parsed value: 00:44:36
[2019-09-24 13:51:45,168] INFO [Titandash Instance 3] [stats.py:332 - update_prestige() ] attempting to parse hours, minutes and seconds from parsed text.
[2019-09-24 13:51:45,175] INFO [Titandash Instance 3] [stats.py:343 - update_prestige() ] generating new prestige instance
[2019-09-24 13:51:45,183] ERROR [Titandash Instance 3] [stats.py:363 - update_prestige() ] error occurred while creating a prestige instance.
[2019-09-24 13:51:45,189] ERROR [Titandash Instance 3] [stats.py:364 - update_prestige() ] Artifact matching query does not exist.
[2019-09-24 13:51:45,196] CRITICAL [Titandash Instance 3] [bot.py:1752 - run() ] critical error encountered: cannot unpack non-iterable NoneType object
Traceback (most recent call last):
  File "C:\Users\LiaM\titandash\titanbot\titandash\bot\core\bot.py", line 1745, in run
    wait_afterwards(getattr(self, func), floor=self.configuration.post_action_min_wait_time, ceiling=self.configuration.post_action_max_wait_time)()
  File "C:\Users\LiaM\titandash\titanbot\titandash\bot\core\decorators.py", line 45, in wrapped
    function(*args, **kwargs)
  File "C:\Users\LiaM\titandash\titanbot\titandash\bot\core\decorators.py", line 58, in current_function
    return function(*args, **kwargs)
  File "C:\Users\LiaM\titandash\titanbot\titandash\bot\core\decorators.py", line 36, in in_transition
    return function(*args, **kwargs)
  File "C:\Users\LiaM\titandash\titanbot\titandash\bot\core\bot.py", line 753, in prestige
    prestige, advanced_start = self.stats.update_prestige(artifact=self.next_artifact_upgrade, current_stage=self.props.current_stage)
TypeError: cannot unpack non-iterable NoneType object
[2019-09-24 13:51:45,205] INFO [Titandash Instance 3] [bot.py:1753 - run() ] terminating!
[2019-09-24 13:51:45,232] INFO [Titandash Instance 3] [bot.py:1768 - run() ] ==========================================================================================
[2019-09-24 13:51:45,239] INFO [Titandash Instance 3] [bot.py:1769 - run() ] Titandash Instance 3 [Session [e3520632-89b4-40fb-8631-2fb6cb8e1d27] v1.5.3]
[2019-09-24 13:51:45,244] INFO [Titandash Instance 3] [bot.py:1770 - run() ] ==========================================================================================
```

The fix for this error in 1.5.3 is to make sure the configuration options:

`Enable Artifact Purchase = True`
`Upgrade Owned Artifacts = True`

Users should be able to disable these settings if they wish and disable the artifact purchase functionality.

Some investigation will be needed into these flags.. Condense them into one if possible. Since you can only upgrade owned artifacts anyways. Maybe it makes more sense to just iterate through owned artifacts if you've enabled artifact purchase functionality.

**Comment by becurrie** [comment]
Resolved by #192
