### ISSUE TITLE
Git Installed Without Using Repository

### ISSUE THREAD

**Issue by becurrie** [becurrie/titandash#188]
Doh! Didn't think of this case. If a user has git installed but is not using the repository (they downloaded the package). An error is thrown. I do not believe this error is fatal or anything, but it's a bit noisy and un-neccessary, we can throw this in it's own exception block and do a lower level log.

```
Traceback (most recent call last):
  File "D:\Program Files\Games\Taptitans 2 bot\titandash-master\settings.py", line 55, in <module>
    GIT_COMMIT = git.Repo(ROOT_DIR).head.commit.hexsha
  File "C:\Users\soj\Envs\titandash\lib\site-packages\git\repo\base.py", line 184, in init
    raise InvalidGitRepositoryError(epath)
git.exc.InvalidGitRepositoryError: D:\Program Files\Games\Taptitans 2 bot\titandash-master
No changes detected
D:\Program Files\Games\Taptitans 2 bot\titandash-master
Traceback (most recent call last):
  File "D:\Program Files\Games\Taptitans 2 bot\titandash-master\settings.py", line 55, in <module>
    GIT_COMMIT = git.Repo(ROOT_DIR).head.commit.hexsha
  File "C:\Users\soj\Envs\titandash\lib\site-packages\git\repo\base.py", line 184, in init
    raise InvalidGitRepositoryError(epath)
git.exc.InvalidGitRepositoryError: D:\Program Files\Games\Taptitans 2 bot\titandash-master
```

**Comment by becurrie** [comment]
Resolved by #191
