### ISSUE TITLE
Time Played Statistics Issue

### ISSUE THREAD

**Issue by becurrie** [becurrie/titandash#207]
Issue found when parsing statistics for time played...

```
Internal Server Error: /statistics
Traceback (most recent call last):
  File "C:\Users\Heather\Envs\titandash\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Heather\Envs\titandash\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Heather\Envs\titandash\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Heather\Desktop\titandash\titanbot\titandash\views.py", line 143, in statistics
    return render(request, "statistics/allStatistics.html", context=ctx)
  File "C:\Users\Heather\Envs\titandash\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\Heather\Envs\titandash\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\Heather\Envs\titandash\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\Heather\Envs\titandash\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "C:\Users\Heather\Envs\titandash\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\Heather\Envs\titandash\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "C:\Users\Heather\Envs\titandash\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "C:\Users\Heather\Envs\titandash\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "C:\Users\Heather\Envs\titandash\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\Heather\Envs\titandash\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "C:\Users\Heather\Envs\titandash\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "C:\Users\Heather\Envs\titandash\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "C:\Users\Heather\Envs\titandash\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "C:\Users\Heather\Envs\titandash\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "C:\Users\Heather\Envs\titandash\lib\site-packages\django\template\loader_tags.py", line 188, in render
    return template.render(context)
  File "C:\Users\Heather\Envs\titandash\lib\site-packages\django\template\base.py", line 173, in render
    return self._render(context)
  File "C:\Users\Heather\Envs\titandash\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\Heather\Envs\titandash\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "C:\Users\Heather\Envs\titandash\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "C:\Users\Heather\Envs\titandash\lib\site-packages\django\template\base.py", line 987, in render
    output = self.filter_expression.resolve(context)
  File "C:\Users\Heather\Envs\titandash\lib\site-packages\django\template\base.py", line 671, in resolve
    obj = self.var.resolve(context)
  File "C:\Users\Heather\Envs\titandash\lib\site-packages\django\template\base.py", line 796, in resolve
    value = self._resolve_lookup(context)
  File "C:\Users\Heather\Envs\titandash\lib\site-packages\django\template\base.py", line 858, in _resolve_lookup
    current = current()
  File "C:\Users\Heather\Desktop\titandash\titanbot\titandash\models\statistics.py", line 77, in time_played_average
    played = int(played.split("d")[0])
ValueError: invalid literal for int() with base 10: 'Time: 12:02:55'
```

If someone doesn't have a day played yet... No d is present and this causes an error when parsing to display data.

Some fixes should be put in place to only allow the value to contain a "d" and also add support for < 24 hours of time played so the split process still works properly.

**Comment by becurrie** [comment]
Resolved by #213
